# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=2500)),
            ],
        ),
    ]
